// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApv7xL6dHviFQFpVfBbLritucaWjIxNlU',
    appId: '1:393868583614:web:87f46f11674a1a02cd74ef',
    messagingSenderId: '393868583614',
    projectId: 'rentapp-b8478',
    authDomain: 'rentapp-b8478.firebaseapp.com',
    storageBucket: 'rentapp-b8478.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0MOMJIYDx3bezRnckNJ0UHe_ZlzP7l5E',
    appId: '1:393868583614:android:190cbbf93210c088cd74ef',
    messagingSenderId: '393868583614',
    projectId: 'rentapp-b8478',
    storageBucket: 'rentapp-b8478.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWXqvnVGb_5dibFkLS5xhn-CRXIxmWOR0',
    appId: '1:393868583614:ios:6e8d7bf75eca2b7ccd74ef',
    messagingSenderId: '393868583614',
    projectId: 'rentapp-b8478',
    storageBucket: 'rentapp-b8478.firebasestorage.app',
    iosBundleId: 'com.example.rentapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWXqvnVGb_5dibFkLS5xhn-CRXIxmWOR0',
    appId: '1:393868583614:ios:6e8d7bf75eca2b7ccd74ef',
    messagingSenderId: '393868583614',
    projectId: 'rentapp-b8478',
    storageBucket: 'rentapp-b8478.firebasestorage.app',
    iosBundleId: 'com.example.rentapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApv7xL6dHviFQFpVfBbLritucaWjIxNlU',
    appId: '1:393868583614:web:920d1f112ea04ffccd74ef',
    messagingSenderId: '393868583614',
    projectId: 'rentapp-b8478',
    authDomain: 'rentapp-b8478.firebaseapp.com',
    storageBucket: 'rentapp-b8478.firebasestorage.app',
  );

}